concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
jobs:
  build:
    uses: ./.github/workflows/test.yml
  pull-request:
    name: Pull request success
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: 'true'
name: Pull request
on:
  repository_dispatch:
    types: trigger-ga___pull_request.yml
